platform :ios,'7.0'
pod 'DKNightVersion','~> 1.2'
pod 'UMengSocial','~> 5.0'
pod 'Masonry', '~> 0.6.4'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.0.4'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'SDWebImage', '~> 3.7.5'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'YYText', '~> 1.0.5'
